# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='goods',
            index_together=set([]),
        ),
    ]
