# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171126_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(db_column='slug', max_length=200),
        ),
    ]
